### ISSUE TITLE
Problem on Ubuntu 22.04

### ISSUE THREAD

**Issue by adamoxford** [search5/Evernote-for-Linux#5]
Thanks for a really awesome package for Evernote - better than the private beta. 

Since updating to Ubuntu 22.04, I've noticed an issue on one machine (but not on another). App starts then immediately crashes with following log:

[2022-05-18T15:25:56.498Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info): client:utils:PerformanceLogger ELECTRON_INITIALIZATION took: 1400 ms (topicName=client:utils:PerformanceLogger)
[2022-05-18T15:25:56.508Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info): client:utils:PerformanceLogger APP_INITIALIZATION started: 1560 (topicName=client:utils:PerformanceLogger)
[2022-05-18T15:25:56.508Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info):  Main app ready {"sender":{"userAgentFallback":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) evernote-client/10.34.4 Chrome/89.0.4389.128 Electron/12.2.3 Safari/537.36","allowRendererProcessReuse":true,"commandLine":{},"isPackaged":true,"_events":{},"_eventsCount":11}}
(node:121982) UnhandledPromiseRejectionWarning: TypeError: c.PromiseBuffer is not a constructor
    at K.e (/usr/lib/evernote-client/resources/app/main.js:2:55293)
    at new t (/usr/lib/evernote-client/resources/app/main.js:2:24917)
    at new K (/usr/lib/evernote-client/resources/app/main.js:852:24853)
    at MainBackend._setupTransport (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/dist/main/backend.js:115:20)
    at MainBackend.BaseBackend (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/node_modules/@sentry/core/dist/basebackend.js:15:32)
    at new MainBackend (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/dist/main/backend.js:59:24)
    at MainClient.BaseClient (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/node_modules/@sentry/core/dist/baseclient.js:52:25)
    at new MainClient (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/dist/main/client.js:17:23)
    at Object.initAndBind (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/node_modules/@sentry/core/dist/sdk.js:18:18)
    at Object.init (/usr/lib/evernote-client/resources/app/node_modules/@sentry/electron/dist/main/index.js:53:12)
(Use `evernote-client --trace-warnings ...` to show where the warning was created)
(node:121982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:121982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-05-18T15:25:56.626Z]  WARN: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:258 in warn): electron:settings Unable to load settings, reverting to defaults Error: ENOENT: no such file or directory, open '/home/yellowbox/.config/evernote-client/localsettings.json' (topicName=electron:settings)
[2022-05-18T15:25:56.628Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info): boron:appProtocol Registering buffer protocol for the session {"defaultSession":{"availableSpellCheckerLanguages":["af","bg","ca","cs","cy","da","de","de-DE","el","en-AU","en-CA","en-GB","en-GB-oxendict","en-US","es","es-419","es-AR","es-ES","es-MX","es-US","et","fa","fo","fr","fr-FR","he","hi","hr","hu","hy","id","it","it-IT","ko","lt","lv","nb","nl","pl","pt","pt-BR","pt-PT","ro","ru","sh","sk","sl","sq","sr","sv","ta","tg","tr","uk","vi"],"spellCheckerEnabled":true,"cookies":{},"netLog":{"currentlyLogging":false},"protocol":{},"serviceWorkers":{},"webRequest":{}}} (topicName=boron:appProtocol)
[2022-05-18T15:25:56.628Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info): boron:appProtocol Registering buffer protocol for the session {"defaultSession":{"availableSpellCheckerLanguages":["af","bg","ca","cs","cy","da","de","de-DE","el","en-AU","en-CA","en-GB","en-GB-oxendict","en-US","es","es-419","es-AR","es-ES","es-MX","es-US","et","fa","fo","fr","fr-FR","he","hi","hr","hu","hy","id","it","it-IT","ko","lt","lv","nb","nl","pl","pt","pt-BR","pt-PT","ro","ru","sh","sk","sl","sq","sr","sv","ta","tg","tr","uk","vi"],"spellCheckerEnabled":true,"cookies":{},"netLog":{"currentlyLogging":false},"protocol":{},"serviceWorkers":{},"webRequest":{}}} (topicName=boron:appProtocol)
[2022-05-18T15:25:56.639Z]  INFO: electron.main/121982 on yellowBox(/usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:248 in info): client:utils:PerformanceLogger CONDUIT_INIT started: 1691 (topicName=client:utils:PerformanceLogger)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[121982:0518/172558.158002:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

**Comment by adamoxford** [comment]
Seems to be a known issue caused by Chromium packaged as a Snap now: 
https://github.com/balena-io/etcher/issues/3639

Can be resolved with the startup flag --disable-gpu-sandbox
